name: Bug report
description: Report a reproducible issue in OpenClawRun
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the issue with simple steps.
        Any language is okay.

  - type: textarea
    id: summary
    attributes:
      label: What happened?
      placeholder: Gateway restart fails and status stays red.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: Gateway should restart and become green.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open OpenClawRun
        2. Click Gateway Stop
        3. Click Gateway Restart
        4. See error
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: OpenClawRun version
      placeholder: v0.1.2

  - type: input
    id: openclaw_version
    attributes:
      label: OpenClaw version
      placeholder: 2026.2.19-2

  - type: input
    id: macos
    attributes:
      label: macOS version
      placeholder: macOS 14.7 / 15.x

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics (optional)
      description: Paste output from "Copy Diagnostics" in OpenClawRun
      render: text
    validations:
      required: false
